_commit: v2.0.0
_src_path: gh:superlinear-ai/substrate
author_email: bszaniecki@pyronsolutions.com
author_name: Bartosz Szaniecki
project_description: A package for simplified push notification management.
project_name: Notificator
project_type: package
project_url: https://github.com/pyron-solutions/notificator
python_version: '3.14'
typing: strict
with_conventional_commits: true
with_typer_cli: false
