site_name: Notificator
site_description: A package for simplified push notification management.
site_url: https://pyron-solutions.github.io/notificator
repo_url: https://github.com/pyron-solutions/notificator
repo_name: pyron-solutions/notificator

strict: true

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

theme:
  name: material

nav:
  - Home: index.md
  - Reference: reference.md

watch:
  - src

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
